### ISSUE TITLE
Console screen flooded with glib errors

### ISSUE THREAD

**Issue by castrojo** [ublue-os/yafti#45] opened 2023-03-19 20:17 UTC
![image](https://user-images.githubusercontent.com/1264109/226206557-5170d916-92ff-4fec-b220-ea2312aed701.png)

Testing this on F38, application installation is working though.

**Comment by abanna** [comment] 2024-05-02 14:05
closing this as the issue is resolved with upcoming release.

**Closed by abanna** 2024-05-02 14:05 UTC
